version: "3.6"

services:
  web_devops:
    image: datata/devops_project
    tty: true
    container_name: web_devops
    restart: unless-stopped
    command: sh -c 'npm install && node index.js'
    ports:
      - "3006:3006"