version: "3.6"

services:
  web_devops:
    image: datata/devops_project
    tty: true
    container_name: web_devops
    restart: unless-stopped
    command: sh -c 'npm install && node index.js'
    ports:
      - "80:3006"

  db_devops:
    image: mongo
    container_name: db_devops
    restart: always
    volumes:
      - /my/own/datadir:/data/db 

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    ports:
      - 9000:9000