name: Backend CI/CD

on:
  push:
    branches:
      - master
      
jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install node dependencies
        run: npm install
      - name: run jest tests
        run: npm test