name: Backend CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      with:
        node-version: '10'
      - name: Install
      run: npm install
      - name: Tests
      run: npm test 